services:
  - type: web
    name: ebay-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: VERIFICATION_TOKEN
        value: mYt0k3nS3cur3eBayW3bh00k2024xZ
      - key: ENDPOINT_URL
        value: https://ebay-webhook.onrender.com/ebay-webhook
